# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import transactions_pb2 as transactions__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x1a\x12transactions.proto\x1a\x1bgoogle/protobuf/empty.proto2\x95\x04\n\x0cTransactions\x12\x64\n\x11TransactionCommit\x12&.transactions.TransactionCommitRequest\x1a\'.transactions.TransactionCommitResponse\x12o\n\x1aTransactionCommitWithSteps\x12&.transactions.TransactionCommitRequest\x1a\'.transactions.TransactionCommitResponse0\x01\x12U\n\x10TransactionsList\x12\x16.google.protobuf.Empty\x1a\'.transactions.TransactionCommitResponse0\x01\x12h\n\x12TransactionsCommit\x12&.transactions.TransactionCommitRequest\x1a(.transactions.TransactionsCommitResponse(\x01\x12m\n\x16\x42ulkTransactionsCommit\x12&.transactions.TransactionCommitRequest\x1a\'.transactions.TransactionCommitResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONS']._serialized_start=64
  _globals['_TRANSACTIONS']._serialized_end=597
# @@protoc_insertion_point(module_scope)
