# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import transactions_pb2 as transactions__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in main_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransactionCommit = channel.unary_unary(
                '/Transactions/TransactionCommit',
                request_serializer=transactions__pb2.TransactionCommitRequest.SerializeToString,
                response_deserializer=transactions__pb2.TransactionCommitResponse.FromString,
                _registered_method=True)
        self.TransactionCommitWithSteps = channel.unary_stream(
                '/Transactions/TransactionCommitWithSteps',
                request_serializer=transactions__pb2.TransactionCommitRequest.SerializeToString,
                response_deserializer=transactions__pb2.TransactionCommitResponse.FromString,
                _registered_method=True)
        self.TransactionsList = channel.unary_stream(
                '/Transactions/TransactionsList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=transactions__pb2.TransactionCommitResponse.FromString,
                _registered_method=True)
        self.TransactionsCommit = channel.stream_unary(
                '/Transactions/TransactionsCommit',
                request_serializer=transactions__pb2.TransactionCommitRequest.SerializeToString,
                response_deserializer=transactions__pb2.TransactionsCommitResponse.FromString,
                _registered_method=True)
        self.BulkTransactionsCommit = channel.stream_stream(
                '/Transactions/BulkTransactionsCommit',
                request_serializer=transactions__pb2.TransactionCommitRequest.SerializeToString,
                response_deserializer=transactions__pb2.TransactionCommitResponse.FromString,
                _registered_method=True)


class TransactionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransactionCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionCommitWithSteps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionsCommit(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkTransactionsCommit(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransactionCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.TransactionCommit,
                    request_deserializer=transactions__pb2.TransactionCommitRequest.FromString,
                    response_serializer=transactions__pb2.TransactionCommitResponse.SerializeToString,
            ),
            'TransactionCommitWithSteps': grpc.unary_stream_rpc_method_handler(
                    servicer.TransactionCommitWithSteps,
                    request_deserializer=transactions__pb2.TransactionCommitRequest.FromString,
                    response_serializer=transactions__pb2.TransactionCommitResponse.SerializeToString,
            ),
            'TransactionsList': grpc.unary_stream_rpc_method_handler(
                    servicer.TransactionsList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=transactions__pb2.TransactionCommitResponse.SerializeToString,
            ),
            'TransactionsCommit': grpc.stream_unary_rpc_method_handler(
                    servicer.TransactionsCommit,
                    request_deserializer=transactions__pb2.TransactionCommitRequest.FromString,
                    response_serializer=transactions__pb2.TransactionsCommitResponse.SerializeToString,
            ),
            'BulkTransactionsCommit': grpc.stream_stream_rpc_method_handler(
                    servicer.BulkTransactionsCommit,
                    request_deserializer=transactions__pb2.TransactionCommitRequest.FromString,
                    response_serializer=transactions__pb2.TransactionCommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transactions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Transactions', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transactions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransactionCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Transactions/TransactionCommit',
            transactions__pb2.TransactionCommitRequest.SerializeToString,
            transactions__pb2.TransactionCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransactionCommitWithSteps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Transactions/TransactionCommitWithSteps',
            transactions__pb2.TransactionCommitRequest.SerializeToString,
            transactions__pb2.TransactionCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransactionsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Transactions/TransactionsList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            transactions__pb2.TransactionCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransactionsCommit(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Transactions/TransactionsCommit',
            transactions__pb2.TransactionCommitRequest.SerializeToString,
            transactions__pb2.TransactionsCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkTransactionsCommit(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/Transactions/BulkTransactionsCommit',
            transactions__pb2.TransactionCommitRequest.SerializeToString,
            transactions__pb2.TransactionCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
