# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transactions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transactions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12transactions.proto\x12\x0ctransactions\"Y\n\x18TransactionCommitRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12,\n\x0e\x61mount_details\x18\x02 \x01(\x0b\x32\x14.transactions.Amount\"*\n\x06\x41mount\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\"\xb4\x01\n\x19TransactionCommitResponse\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.transactions.Status\x12\x30\n\x06reason\x18\x02 \x01(\x0e\x32\x1b.transactions.RejectReasonsH\x00\x88\x01\x01\x12\x17\n\x0freceived_amount\x18\x03 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x04 \x03(\t\x12\n\n\x02id\x18\x05 \x01(\tB\t\n\x07_reason\"\xa8\x01\n\x1aTransactionsCommitResponse\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.transactions.Status\x12\x1d\n\x15total_received_amount\x18\x02 \x01(\x05\x12\x1c\n\x14total_received_count\x18\x03 \x01(\x05\x12\x1b\n\x13total_refused_count\x18\x04 \x01(\x05\x12\n\n\x02id\x18\x05 \x01(\t*4\n\x06Status\x12\r\n\tCOMMITTED\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\x0b\n\x07REFUSED\x10\x02*L\n\rRejectReasons\x12\x11\n\rNOT_SPECIFIED\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x14\n\x10INVALID_ARGUMENT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=525
  _globals['_STATUS']._serialized_end=577
  _globals['_REJECTREASONS']._serialized_start=579
  _globals['_REJECTREASONS']._serialized_end=655
  _globals['_TRANSACTIONCOMMITREQUEST']._serialized_start=36
  _globals['_TRANSACTIONCOMMITREQUEST']._serialized_end=125
  _globals['_AMOUNT']._serialized_start=127
  _globals['_AMOUNT']._serialized_end=169
  _globals['_TRANSACTIONCOMMITRESPONSE']._serialized_start=172
  _globals['_TRANSACTIONCOMMITRESPONSE']._serialized_end=352
  _globals['_TRANSACTIONSCOMMITRESPONSE']._serialized_start=355
  _globals['_TRANSACTIONSCOMMITRESPONSE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
