syntax = "proto3";

import "transactions.proto";
import "google/protobuf/empty.proto";

service Transactions {
    rpc TransactionCommit (transactions.TransactionCommitRequest) returns (transactions.TransactionCommitResponse);
    rpc TransactionCommitWithSteps (transactions.TransactionCommitRequest) returns (stream transactions.TransactionCommitResponse);
    rpc TransactionsList (google.protobuf.Empty) returns (stream transactions.TransactionCommitResponse);
    rpc TransactionsCommit (stream transactions.TransactionCommitRequest) returns (transactions.TransactionCommitResponse);
    rpc BulkTransactionsCommit (stream transactions.TransactionCommitRequest) returns (stream transactions.TransactionCommitResponse);
}
